### ISSUE TITLE
Laravel: command not found

### ISSUE THREAD

**Issue by jtpdev** [UpInside/laravel-pt-BR#1]
I follw the instruction by https://laravel.com/docs/7.x#installing-laravel and laravel command still doens't exist.

![image](https://user-images.githubusercontent.com/28665598/84224120-174c5300-aab2-11ea-97ba-28f7362c24e9.png)

I'm using Ubuntu 18

**Comment by firatdgn** [comment]
You should add laravel command to your $PATH variable. 
Add this command to `~/.profile` file:
$ export PATH=$PATH:/myNewDir
Then run the source command from your teminal :
source ~/.profile

**Comment by jtpdev** [comment]
Thanks man, this solve the issue.
